FROM alpine as builder

WORKDIR /app

COPY . .
RUN yarn build


FROM alpine
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser
WORKDIR /app

COPY --from=builder /app/dist .

CMD ["yarn", "start:prod"]
